version: '3'

services:
  wazuh:
    image: wazuh/wazuh
    container_name: wazuh_container
    ports:
      - "55000:55000"
    environment:
      - WAZUH_API_USERNAME=my_username
      - WAZUH_API_PASSWORD=my_password

  kibana-sdgd:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana_sdgd_container
    ports:
      - "5601:5601"
    depends_on:
      - wazuh

  kibana-chat:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana_chat_container
    ports:
      - "5602:5602"

  fortinet:
    image: custom_fortinet
    container_name: fortinet_container
    ports:
      - "port:port"

  proxy:
    image: nginx:alpine
    container_name: proxy_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  osticket:
    image: campbellsoftwaresolutions/osticket
    container_name: osticket_container
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: osticket_db
      MYSQL_USER: osticket
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: osticket

  osticket_db:
    image: mysql:5.7
    container_name: osticket_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: osticket
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: osticket
    volumes:
      - osticket_db_data:/var/lib/mysql

volumes:
  osticket_db_data: